/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNodesRouteImport } from './routes/_authenticated/nodes'
import { Route as AuthenticatedEggsRouteImport } from './routes/_authenticated/eggs'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedServersIndexRouteImport } from './routes/_authenticated/servers/index'
import { Route as AuthenticatedServersNewRouteImport } from './routes/_authenticated/servers/new'
import { Route as AuthenticatedServersServerIdRouteImport } from './routes/_authenticated/servers/$serverId'
import { Route as ApiPublicNodesHeartbeatRouteImport } from './routes/api/public/nodes.heartbeat'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNodesRoute = AuthenticatedNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEggsRoute = AuthenticatedEggsRouteImport.update({
  id: '/eggs',
  path: '/eggs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServersIndexRoute =
  AuthenticatedServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServersNewRoute = AuthenticatedServersNewRouteImport.update({
  id: '/servers/new',
  path: '/servers/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServersServerIdRoute =
  AuthenticatedServersServerIdRouteImport.update({
    id: '/servers/$serverId',
    path: '/servers/$serverId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicNodesHeartbeatRoute = ApiPublicNodesHeartbeatRouteImport.update({
  id: '/api/public/nodes/heartbeat',
  path: '/api/public/nodes/heartbeat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/eggs': typeof AuthenticatedEggsRoute
  '/nodes': typeof AuthenticatedNodesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/servers/$serverId': typeof AuthenticatedServersServerIdRoute
  '/servers/new': typeof AuthenticatedServersNewRoute
  '/servers/': typeof AuthenticatedServersIndexRoute
  '/api/public/nodes/heartbeat': typeof ApiPublicNodesHeartbeatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/eggs': typeof AuthenticatedEggsRoute
  '/nodes': typeof AuthenticatedNodesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/users': typeof AuthenticatedUsersRoute
  '/servers/$serverId': typeof AuthenticatedServersServerIdRoute
  '/servers/new': typeof AuthenticatedServersNewRoute
  '/servers': typeof AuthenticatedServersIndexRoute
  '/api/public/nodes/heartbeat': typeof ApiPublicNodesHeartbeatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/eggs': typeof AuthenticatedEggsRoute
  '/_authenticated/nodes': typeof AuthenticatedNodesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/servers/$serverId': typeof AuthenticatedServersServerIdRoute
  '/_authenticated/servers/new': typeof AuthenticatedServersNewRoute
  '/_authenticated/servers/': typeof AuthenticatedServersIndexRoute
  '/api/public/nodes/heartbeat': typeof ApiPublicNodesHeartbeatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/docs'
    | '/eggs'
    | '/nodes'
    | '/settings'
    | '/users'
    | '/servers/$serverId'
    | '/servers/new'
    | '/servers/'
    | '/api/public/nodes/heartbeat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/docs'
    | '/eggs'
    | '/nodes'
    | '/settings'
    | '/users'
    | '/servers/$serverId'
    | '/servers/new'
    | '/servers'
    | '/api/public/nodes/heartbeat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/docs'
    | '/_authenticated/eggs'
    | '/_authenticated/nodes'
    | '/_authenticated/settings'
    | '/_authenticated/users'
    | '/_authenticated/servers/$serverId'
    | '/_authenticated/servers/new'
    | '/_authenticated/servers/'
    | '/api/public/nodes/heartbeat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiPublicNodesHeartbeatRoute: typeof ApiPublicNodesHeartbeatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/nodes': {
      id: '/_authenticated/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof AuthenticatedNodesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/eggs': {
      id: '/_authenticated/eggs'
      path: '/eggs'
      fullPath: '/eggs'
      preLoaderRoute: typeof AuthenticatedEggsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/': {
      id: '/_authenticated/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthenticatedServersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/new': {
      id: '/_authenticated/servers/new'
      path: '/servers/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof AuthenticatedServersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/$serverId': {
      id: '/_authenticated/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof AuthenticatedServersServerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/nodes/heartbeat': {
      id: '/api/public/nodes/heartbeat'
      path: '/api/public/nodes/heartbeat'
      fullPath: '/api/public/nodes/heartbeat'
      preLoaderRoute: typeof ApiPublicNodesHeartbeatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedEggsRoute: typeof AuthenticatedEggsRoute
  AuthenticatedNodesRoute: typeof AuthenticatedNodesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedServersServerIdRoute: typeof AuthenticatedServersServerIdRoute
  AuthenticatedServersNewRoute: typeof AuthenticatedServersNewRoute
  AuthenticatedServersIndexRoute: typeof AuthenticatedServersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedEggsRoute: AuthenticatedEggsRoute,
  AuthenticatedNodesRoute: AuthenticatedNodesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedServersServerIdRoute: AuthenticatedServersServerIdRoute,
  AuthenticatedServersNewRoute: AuthenticatedServersNewRoute,
  AuthenticatedServersIndexRoute: AuthenticatedServersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiPublicNodesHeartbeatRoute: ApiPublicNodesHeartbeatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
