/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDocsRouteImport } from './routes/_authenticated/docs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedServersIndexRouteImport } from './routes/_authenticated/servers/index'
import { Route as AuthenticatedServersNewRouteImport } from './routes/_authenticated/servers/new'
import { Route as AuthenticatedServersServerIdRouteImport } from './routes/_authenticated/servers/$serverId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDocsRoute = AuthenticatedDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServersIndexRoute =
  AuthenticatedServersIndexRouteImport.update({
    id: '/servers/',
    path: '/servers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServersNewRoute = AuthenticatedServersNewRouteImport.update({
  id: '/servers/new',
  path: '/servers/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServersServerIdRoute =
  AuthenticatedServersServerIdRouteImport.update({
    id: '/servers/$serverId',
    path: '/servers/$serverId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/servers/$serverId': typeof AuthenticatedServersServerIdRoute
  '/servers/new': typeof AuthenticatedServersNewRoute
  '/servers/': typeof AuthenticatedServersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/docs': typeof AuthenticatedDocsRoute
  '/servers/$serverId': typeof AuthenticatedServersServerIdRoute
  '/servers/new': typeof AuthenticatedServersNewRoute
  '/servers': typeof AuthenticatedServersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/docs': typeof AuthenticatedDocsRoute
  '/_authenticated/servers/$serverId': typeof AuthenticatedServersServerIdRoute
  '/_authenticated/servers/new': typeof AuthenticatedServersNewRoute
  '/_authenticated/servers/': typeof AuthenticatedServersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/docs'
    | '/servers/$serverId'
    | '/servers/new'
    | '/servers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard'
    | '/docs'
    | '/servers/$serverId'
    | '/servers/new'
    | '/servers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/dashboard'
    | '/_authenticated/docs'
    | '/_authenticated/servers/$serverId'
    | '/_authenticated/servers/new'
    | '/_authenticated/servers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/': {
      id: '/_authenticated/servers/'
      path: '/servers'
      fullPath: '/servers/'
      preLoaderRoute: typeof AuthenticatedServersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/new': {
      id: '/_authenticated/servers/new'
      path: '/servers/new'
      fullPath: '/servers/new'
      preLoaderRoute: typeof AuthenticatedServersNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servers/$serverId': {
      id: '/_authenticated/servers/$serverId'
      path: '/servers/$serverId'
      fullPath: '/servers/$serverId'
      preLoaderRoute: typeof AuthenticatedServersServerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocsRoute: typeof AuthenticatedDocsRoute
  AuthenticatedServersServerIdRoute: typeof AuthenticatedServersServerIdRoute
  AuthenticatedServersNewRoute: typeof AuthenticatedServersNewRoute
  AuthenticatedServersIndexRoute: typeof AuthenticatedServersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocsRoute: AuthenticatedDocsRoute,
  AuthenticatedServersServerIdRoute: AuthenticatedServersServerIdRoute,
  AuthenticatedServersNewRoute: AuthenticatedServersNewRoute,
  AuthenticatedServersIndexRoute: AuthenticatedServersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
